/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proj_interdisplinar_II;

import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Luans
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form Consulta_cadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CombBxMarcas = new javax.swing.JComboBox<>();
        CombBxModelos = new javax.swing.JComboBox<>();
        txtPlaca = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtPreço = new javax.swing.JTextField();
        CombBxEstado = new javax.swing.JComboBox<>();
        CombBxLoja = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnCancelarInsert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar novo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CombBxMarcas.setModel(new DefaultComboBoxModel());
        CombBxMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombBxMarcasActionPerformed(evt);
            }
        });
        getContentPane().add(CombBxMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, -1));

        CombBxModelos.setModel(new DefaultComboBoxModel());
        CombBxModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombBxModelosActionPerformed(evt);
            }
        });
        getContentPane().add(CombBxModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 71, -1));
        getContentPane().add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 67, 20));
        getContentPane().add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 52, 60, -1));

        txtPreço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreçoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPreço, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 52, 50, -1));

        CombBxEstado.setModel(new DefaultComboBoxModel());
        getContentPane().add(CombBxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 49, 50, -1));

        CombBxLoja.setModel(new DefaultComboBoxModel());
        getContentPane().add(CombBxLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 49, 108, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Marca");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modelo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 63, 19));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Placa");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 60, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ano");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 46, 19));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Preço");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 12, 50, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Estado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 12, 50, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Loja");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 12, 108, 19));

        btnInsert.setText("Cadastrar novo");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 118, -1, -1));

        btnCancelarInsert.setText("Cancelar");
        btnCancelarInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 118, -1, -1));

        setSize(new java.awt.Dimension(628, 221));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    ResultSet results = null;
    ResultSet results2 = null;
    Banco banco = new Banco();
    cadastro_Veiculo vh = new cadastro_Veiculo();
    private void txtPreçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreçoActionPerformed

    private void CombBxMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombBxMarcasActionPerformed
        String marcaSecionada = (String) CombBxMarcas.getSelectedItem();
        System.out.println(marcaSecionada);
        DefaultComboBoxModel cbxModelos = (DefaultComboBoxModel) CombBxModelos.getModel();
        cbxModelos.removeAllElements();
        String query = "select distinct nome_Modelo from marca_e_modelo where nome_Marca = '" + marcaSecionada + "' order by nome_Modelo;";
        try {
            banco.iniciaConexao();
            results2 = banco.statement.executeQuery(query);
            while (results2.next()) {
                cbxModelos.addElement(results2.getString("nome_Modelo"));
            }

        } catch (Exception e) {
        } finally {
            banco.finalizaConexao();
        }
    }//GEN-LAST:event_CombBxMarcasActionPerformed

    private void CombBxModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombBxModelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CombBxModelosActionPerformed

    private void btnCancelarInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarInsertActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarInsertActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String nome_Modelo = (String) CombBxModelos.getSelectedItem();
        String nome_Marca = (String) CombBxMarcas.getSelectedItem();
        String nome_loja = (String) CombBxLoja.getSelectedItem();
        String sigla_Estado = (String) CombBxEstado.getSelectedItem();
        String placa = txtPlaca.getText();
        String ano = txtAno.getText();
        String preco = txtPreço.getText();

        if (!placa.isEmpty() && !ano.isEmpty() && !preco.isEmpty()) {
            String query = "INSERT INTO veiculo (placa,ano,preco,sigla_estado,nome_Loja,nome_Marca,nome_Modelo) values('" + placa + "'," + ano + "," + preco + ",'" + sigla_Estado + "','" + nome_loja + "','" + nome_Marca + "','" + nome_Modelo + "')";
            System.out.println(query);
            try {
                banco.iniciaConexao();

                int res = banco.statement.executeUpdate(query);
                if (res > 0) {
                    System.out.print("Cadastro feito com sucesso.");
                } else {
                    System.out.print("O VEICULO não foi inserida!");
                }

            } catch (Exception e) {
            } finally {
                banco.finalizaConexao();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Preecha todos campos");
        }
        
        this.dispose();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listar_marca();
        listar_estado();
        listar_loja();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        vh.exibirJtable();
    }//GEN-LAST:event_formWindowClosing

    public void listar_marca() {
        DefaultComboBoxModel cbxMarcas = (DefaultComboBoxModel) CombBxMarcas.getModel();

        String query = "select distinct nome_Marca from marca_e_modelo order by nome_Marca;";
        String str = "";
        try {
            banco.iniciaConexao();
            results = banco.statement.executeQuery(query);

            while (results.next()) {
                cbxMarcas.addElement(results.getString("nome_Marca"));
            }

        } catch (Exception e) {
        } finally {
            banco.finalizaConexao();
        }

    }

    public void listar_estado() {
        DefaultComboBoxModel cbxEstado = (DefaultComboBoxModel) CombBxEstado.getModel();

        String query = "select sigla_Estado from estado order by sigla_Estado;";
        String str = "";
        try {
            banco.iniciaConexao();
            results = banco.statement.executeQuery(query);

            while (results.next()) {
                cbxEstado.addElement(results.getString("sigla_Estado"));
            }

        } catch (Exception e) {
        } finally {
            banco.finalizaConexao();
        }

    }

    public void listar_loja() {
        DefaultComboBoxModel cbxLoja = (DefaultComboBoxModel) CombBxLoja.getModel();

        String query = "select nome_Loja from loja order by nome_Loja;";
        String str = "";
        try {
            banco.iniciaConexao();
            results = banco.statement.executeQuery(query);

            while (results.next()) {
                cbxLoja.addElement(results.getString("nome_Loja"));
            }

        } catch (Exception e) {
        } finally {
            banco.finalizaConexao();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CombBxEstado;
    private javax.swing.JComboBox<String> CombBxLoja;
    private javax.swing.JComboBox<String> CombBxMarcas;
    private javax.swing.JComboBox<String> CombBxModelos;
    private javax.swing.JButton btnCancelarInsert;
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPreço;
    // End of variables declaration//GEN-END:variables
}
